{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintMy where

-- pretty-printer generated by the BNF converter

import AbsMy
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print Def where
  prt i e = case e of
    DField mod id exp -> prPrec i 0 (concatD [prt 0 mod, prt 0 id, doc (showString "="), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Mod where
  prt i e = case e of
    MVal -> prPrec i 0 (concatD [doc (showString "val")])
    MVar -> prPrec i 0 (concatD [doc (showString "var")])

instance Print Stm where
  prt i e = case e of
    SEAsign id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    SArrAsign id exp1 exp2 -> prPrec i 0 (concatD [prt 0 id, doc (showString "["), prt 0 exp1, doc (showString "]"), doc (showString "="), prt 0 exp2, doc (showString ";")])
    SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    SDef def -> prPrec i 0 (concatD [prt 0 def, doc (showString ";")])
    SInc id -> prPrec i 0 (concatD [prt 0 id, doc (showString "++"), doc (showString ";")])
    SDec id -> prPrec i 0 (concatD [prt 0 id, doc (showString "--"), doc (showString ";")])
    SReturnE exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    SReturn -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), prt 0 exp, doc (showString "do"), prt 0 stm])
    SFor id exp1 exp2 stm -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "val"), prt 0 id, doc (showString "="), prt 0 exp1, doc (showString "to"), prt 0 exp2, doc (showString "do"), prt 0 stm])
    SForEach id1 id2 stm -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "val"), prt 0 id1, doc (showString ":"), prt 0 id2, doc (showString "do"), prt 0 stm])
    SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString "then"), prt 0 stm, doc (showString "fi")])
    SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString "then"), prt 0 stm1, doc (showString "else"), prt 0 stm2, doc (showString "fi")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Type where
  prt i e = case e of
    Tbool -> prPrec i 0 (concatD [doc (showString "bool")])
    Tint -> prPrec i 0 (concatD [doc (showString "int")])
    Tvoid -> prPrec i 0 (concatD [doc (showString "void")])
    TString -> prPrec i 0 (concatD [doc (showString "string")])
    TFun types type_ -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "("), doc (showString "("), prt 0 types, doc (showString ")"), doc (showString "=>"), prt 0 type_, doc (showString ")")])
    TArray type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Arg where
  prt i e = case e of
    ADecl mod id type_ -> prPrec i 0 (concatD [prt 0 mod, prt 0 id, doc (showString ":"), prt 0 type_])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Exp where
  prt i e = case e of
    EHi exp -> prPrec i 15 (concatD [doc (showString "("), prt 0 exp, doc (showString ")")])
    EIdent id -> prPrec i 14 (concatD [prt 0 id])
    EInt n -> prPrec i 14 (concatD [prt 0 n])
    EString str -> prPrec i 14 (concatD [prt 0 str])
    ETrue -> prPrec i 14 (concatD [doc (showString "true")])
    EFalse -> prPrec i 14 (concatD [doc (showString "false")])
    EFun args type_ stm -> prPrec i 14 (concatD [doc (showString "("), prt 0 args, doc (showString ")"), doc (showString ":"), prt 0 type_, doc (showString "=>"), prt 0 stm])
    EAppFun id exps -> prPrec i 14 (concatD [prt 0 id, doc (showString "("), prt 0 exps, doc (showString ")")])
    EArrIni type_ exp -> prPrec i 14 (concatD [doc (showString "new"), prt 0 type_, doc (showString "["), prt 0 exp, doc (showString "]")])
    EArrLen id -> prPrec i 14 (concatD [prt 0 id, doc (showString ".length")])
    EArrAcc id exp -> prPrec i 14 (concatD [prt 0 id, doc (showString "["), prt 0 exp, doc (showString "]")])
    ENeg exp -> prPrec i 13 (concatD [doc (showString "-"), prt 14 exp])
    EMul exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    EDiv exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "/"), prt 12 exp2])
    EPlus exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "+"), prt 11 exp2])
    EMinus exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "-"), prt 10 exp2])
    ENot exp -> prPrec i 8 (concatD [doc (showString "!"), prt 9 exp])
    ELt exp1 exp2 -> prPrec i 7 (concatD [prt 7 exp1, doc (showString ">"), prt 8 exp2])
    EGt exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "<"), prt 7 exp2])
    EGtEq exp1 exp2 -> prPrec i 5 (concatD [prt 5 exp1, doc (showString ">="), prt 6 exp2])
    ELtEq exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "<="), prt 5 exp2])
    EEq exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "=="), prt 4 exp2])
    ENeq exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "!="), prt 3 exp2])
    EAnd exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "&&"), prt 2 exp2])
    EOr exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "||"), prt 1 exp2])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])

